### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by Death-777** [ExponentialML/Text-To-Video-Finetuning#10]
After running the train.py I get this RuntimeError:

`C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
03/24/2023 08:52:48 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

{'variance_type'} was not found in config. Values will be initialized to default values.
C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
{'downsample_padding', 'mid_block_scale_factor'} was not found in config. Values will be initialized to default values.
03/24/2023 08:52:50 - INFO - __main__ - ***** Running training *****
03/24/2023 08:52:50 - INFO - __main__ -   Num examples = 1
03/24/2023 08:52:50 - INFO - __main__ -   Num Epochs = 1200
03/24/2023 08:52:50 - INFO - __main__ -   Instantaneous batch size per device = 1
03/24/2023 08:52:50 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
03/24/2023 08:52:50 - INFO - __main__ -   Gradient Accumulation steps = 1
03/24/2023 08:52:50 - INFO - __main__ -   Total optimization steps = 1200
Steps:   0%|                                                                                                                   | 0/1200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\Art\Text-To-Video-Finetuning\train.py", line 498, in <module>
    main(**OmegaConf.load(args.config))
  File "D:\Art\Text-To-Video-Finetuning\train.py", line 394, in main
    loss, latents = finetune_unet(batch, train_encoder=train_text_encoder)
  File "D:\Art\Text-To-Video-Finetuning\train.py", line 339, in finetune_unet
    latents = tensor_to_vae_latent(pixel_values, vae)
  File "D:\Art\Text-To-Video-Finetuning\train.py", line 157, in tensor_to_vae_latent
    latents = vae.encode(t).latent_dist.sample()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\autoencoder_kl.py", line 164, in encode
    h = self.encoder(x)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\vae.py", line 109, in forward
    sample = self.conv_in(sample)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Steps:   0%|                                                                                                                   | 0/1200 [00:00<?, ?it/s]`

**Comment by ExponentialML** [comment]
Are you trying to run on CPU? Only GPU training is supported.

If you're using accelerate, you could try these in the command line.

`accelerate config`

You will be prompted with instructions on setting up. Then you should be able to do the following.

`accelerate launch train.py --config ./configs/my_config_file.yaml`

**Comment by Death-777** [comment]
I'm not trying to run on CPU, but it seems to be trying to anyway. How do I get it to run off my GPU instead?
I'm using accelerate and configured it but I'm not entirely sure I configured it correctly.
After running that second line you gave me I get this

 Device: cpu
Traceback (most recent call last):
  File "D:\Art\Text-To-Video-Finetuning\train.py", line 501, in <module>
    main(**OmegaConf.load(args.config))
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\omegaconf\omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Art\\Text-To-Video-Finetuning\\configs\\my_config_file.yaml'
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\User1\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train.py', '--config', './configs/my_config_file.yaml']' returned non-zero exit status 1.

same problem, it's trying to run off of my CPU and I don't know why.

**Comment by ExponentialML** [comment]
> same problem, it's trying to run off of my CPU and I don't know why.

Interesting. It could be that you've installed the CPU version of Pytorch and not the GPU version.

Could you try reinstalling Pytorch with this command?

```bash
pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by Cubey42** [comment]
this is like the issue I had, you want to download the entire repo, (all models, not just the fp16)

**Comment by Death-777** [comment]
That did the trick, after installing the proper version of Pytorch it works fine now. Thanks 👍

**Comment by ExponentialML** [comment]
@Death-777 Glad to hear you fixed it!
