### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'config'

### ISSUE THREAD

**Issue by howardgriffin** [ExponentialML/Text-To-Video-Finetuning#106]
Has anyone encountered this problem, and how to solve it?

Traceback (most recent call last):
  File "train.py", line 958, in <module>
    main(**OmegaConf.load(args.config))
  File "train.py", line 828, in main
    loss, latents = finetune_unet(batch, train_encoder=train_text_encoder)
  File "train.py", line 765, in finetune_unet
    encoder_hidden_states = text_encoder(token_ids)[0]
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 821, in forward
    return_dict = return_dict if return_dict is not None else self.config.use_return_dict
AttributeError: 'Tensor' object has no attribute 'config''
Steps:  25%|█████████████████████                                                               | 2500/10000 [1:18:08<3:54:26,  1.88s/it, lr=5e-6, step_loss=0.0105]

**Comment by ExponentialML** [comment]
Hello. Could you try upgrading Transformers and see if that helps? `pip install transformers -U`

**Comment by howardgriffin** [comment]
Hello，
It may not be a transformers problem, I upgraded to the latest 4.31.0 version, and this error still occurs.
But I'm sure it's an environmental problem. I used another image and it can run correctly, but I still don't know where the problem is.

**Comment by naeemtee** [comment]
@howardgriffin were you able to figure this out?

**Comment by ExponentialML** [comment]
Hey @howardgriffin and @xnmt9 , apologizes for the late response. I've pushed a fix here to as seen here https://github.com/ExponentialML/Text-To-Video-Finetuning/pull/120/commits/563a1a4eaafec799731481d16eaeb1398e749907 . Could you pull the latest changes and see if it works please?

**Comment by ExponentialML** [comment]
Closing this as it seems to fix the issue. Please feel free to re-open if the issue persists.
