### ISSUE TITLE
[inference] latents_window index error

### ISSUE THREAD

**Issue by IceTea42** [ExponentialML/Text-To-Video-Finetuning#138]
Hi, thanks for your work and sharing it.

When I use the inference with exact same arguments written as in ReadMe (except for a smaller resolution), I've got this error about multistep_dpm_solver.

Do you have any suggestions on this?  

(t2v) jupyter@pc:~/src/Text-To-Video-Finetuning$ python inference.py   --model camenduru/potat1   --prompt "a fast moving fancy sports car"   --num-frames 60   --window-size 12   --width 256   --height 192   --sdp
Initializing the conversion map
Loading pipeline components...: 100%|██████████████████████████████████████████████████████| 5/5 [00:00<00:00, 53.18it/s]
33 Attention layers using Scaled Dot Product Attention.
/opt/conda/envs/t2v/lib/python3.10/site-packages/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py:160: FutureWarning: `_encode_prompt()` is deprecated and it will be removed in a future version. Use `encode_prompt()` instead. Also, be aware that the output format changed from a concatenated tensor to a tuple.
  deprecate("_encode_prompt()", "1.0.0", deprecation_message, standard_warn=False)
Diffusing timestep 799...:  20%|███████████▏                                            | 25/125 [00:17<01:08,  1.45it/s]
Traceback (most recent call last):
  File "/home/jupyter/src/Text-To-Video-Finetuning/inference.py", line 396, in <module>
    videos = inference(
  File "/opt/conda/envs/t2v/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jupyter/src/Text-To-Video-Finetuning/inference.py", line 316, in inference
    latents = diffuse(
  File "/opt/conda/envs/t2v/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jupyter/src/Text-To-Video-Finetuning/inference.py", line 245, in diffuse
    latents_window = pipe.scheduler.step(noise_pred, t, latents_window).prev_sample
  File "/opt/conda/envs/t2v/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 812, in step
    prev_sample = self.multistep_dpm_solver_second_order_update(self.model_outputs, sample=sample, noise=noise)
  File "/opt/conda/envs/t2v/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 568, in multistep_dpm_solver_second_order_update
    self.sigmas[self.step_index + 1],
IndexError: index 26 is out of bounds for dimension 0 with size 26

**Comment by IceTea42** [comment]
In case someone else has the same problem: I fixed it by downgrading to diffusers==0.20.2 (mine was 0.22.0.dev0)
